using Tyuiu.ZolotovaKA.Sprint2.Task2.V27.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #2| Выполнил: Золотова К. А. | ИСПБ-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #2                                                               *");
Console.WriteLine("* Тема: Создание итогового решения по спринту                             *");
Console.WriteLine("* Задание #2                                                              *");
Console.WriteLine("* Вариант #25                                                             *");
Console.WriteLine("* Выполнил: Золотова К. А. | ИСПБ-24-1                                    *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Написать консольную программу на C#, которая запрашивает целые значения с клавиатуры *");
Console.WriteLine("* и вычисляет находится ли точка с координатами X,Y в заштрихованной области.*");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ: x = 205 y = 159                                        *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
int x, y;
Console.WriteLine("Введите значение переменной X:");
x = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите значение переменной Y:");
y = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
var res = ds.CheckDotInShadedArea(x, y);
if (res)
    Console.WriteLine("Точка находится в заштрихованной области");
else
    Console.WriteLine("Точка не находится в заштрихованной области");
Console.ReadKey();